package servent.message;

public enum MessageType {
	NEW_NODE, WELCOME, SORRY, UPDATE, PUT, ASK_GET, TELL_GET, POISON, PING, WARNING, REMOVE, DEFUSE, BACKUP, FOLLOW_REQUEST, EMERGENCY, SK_REQUEST, SK_REPLY
}
